#!/usr/bin/env python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import subprocess

PLANS = ["Performance", "Balanced", "Power Saver"]
ARGS = [
    "--stapm-limit=15000 --fast-limit=30000 --slow-limit=25000",
    "--stapm-limit=12000 --fast-limit=18000 --slow-limit=15000",
    "--stapm-limit=8000 --fast-limit=12000 --slow-limit=10000"
]
current = 1

def apply(idx):
    global current
    current = idx
    subprocess.run(["sudo", "ryzenadj"] + ARGS[idx].split(), check=False)
    icon.set_tooltip_text(f"Power: {PLANS[idx]}")

def menu(ic, button, time):
    m = Gtk.Menu()
    for i in range(3):
        item = Gtk.MenuItem(label=PLANS[i])
        if i == current:
            item.set_sensitive(False)
        item.connect("activate", lambda _, n=i: apply(n))
        m.append(item)
    m.append(Gtk.SeparatorMenuItem())
    q = Gtk.MenuItem(label="Quit")
    q.connect("activate", lambda _: Gtk.main_quit())
    m.append(q)
    m.show_all()
    m.popup(None, None, None, ic, button, time)

def cycle(ic):
    apply((current + 1) % 3)

icon = Gtk.StatusIcon()
icon.set_from_icon_name("computer")
icon.set_tooltip_text("Power: Balanced")
apply(1)
icon.connect("popup-menu", menu)
icon.connect("activate", cycle)
Gtk.main()
